### ISSUE TITLE
Timeout when running shorten-anonymous.test.js

### ISSUE THREAD

**Issue by UlysC** [suzanje/module-test-puppeteer#4]
Hello I'm trying to set up the project as specified in the README

When running the command `npm run test -- --runInBand`, the test **Shorten Anonymous › basic shorten** fails with a Timeout  

## Steps to reproduce :  
- Clone the repo and run `npm install`
-  Run `npm run test -- --runInBand`  

## Full Error : 
```
FAIL  tests/shorten-anonymous.test.js (15.863s)
  ● Shorten Anonymous › basic shorten

    Timeout - Async callback was not invoked within the 15000ms timeout specified by jest.setTimeout.

       6 | 
       7 |     // vérification du chargement de la page d'accueil
    >  8 |     test('basic shorten', async () => {
         |     ^
       9 |         await page.goto('http://polr.floki.io');
      10 |         await page.waitForSelector('.long-link-input');
      11 |         await page.type('.long-link-input', 'https://www.google.com/search?source=hp&ei=QQbPW52GC9CRlwSHw46oAg&q=puppeteer+jest&oq=puppeteer+jest&gs_l=psy-ab.3...2441.6095.0.6926.0.0.0.0.0.0.0.0..0.0....0...1c.1.64.psy-ab..0.0.0....0.qKd5wLlrTYk');

      at Spec (node_modules/jest-jasmine2/build/jasmine/Spec.js:85:20)
      at Suite.test (tests/shorten-anonymous.test.js:8:5)
```

**Comment by UlysC** [comment]
I have the same Issue

**Comment by UlysC** [comment]
Pls answer :((

**Comment by UlysC** [comment]
Hi,

I ran into a similar issue.

I would suggest turning off your computer, cracking up  cold one, sitting back and relaxing while re evaluating your life choices
Good luck !

**Comment by Clement-Chalencon** [comment]
Please refer to the guidelines as to writing a proper issue thank you

**Comment by Clement-Chalencon** [comment]
And fuck you
